// Code generated by "core generate -add-types"; DO NOT EDIT.

package main

import (
	"cogentcore.org/core/enums"
)

var _PatsTypeValues = []PatsType{0, 1, 2}

// PatsTypeN is the highest valid value for type PatsType, plus one.
const PatsTypeN PatsType = 3

var _PatsTypeValueMap = map[string]PatsType{`Zeroth`: 0, `First`: 1, `Third`: 2}

var _PatsTypeDescMap = map[PatsType]string{0: `zeroth order sequence`, 1: `first order sequence`, 2: `3rd order sequence`}

var _PatsTypeMap = map[PatsType]string{0: `Zeroth`, 1: `First`, 2: `Third`}

// String returns the string representation of this PatsType value.
func (i PatsType) String() string { return enums.String(i, _PatsTypeMap) }

// SetString sets the PatsType value from its string representation,
// and returns an error if the string is invalid.
func (i *PatsType) SetString(s string) error {
	return enums.SetString(i, s, _PatsTypeValueMap, "PatsType")
}

// Int64 returns the PatsType value as an int64.
func (i PatsType) Int64() int64 { return int64(i) }

// SetInt64 sets the PatsType value from an int64.
func (i *PatsType) SetInt64(in int64) { *i = PatsType(in) }

// Desc returns the description of the PatsType value.
func (i PatsType) Desc() string { return enums.Desc(i, _PatsTypeDescMap) }

// PatsTypeValues returns all possible values for the type PatsType.
func PatsTypeValues() []PatsType { return _PatsTypeValues }

// Values returns all possible values for the type PatsType.
func (i PatsType) Values() []enums.Enum { return enums.Values(_PatsTypeValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i PatsType) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *PatsType) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "PatsType") }
